# COE 2022 "GPRA Friendly" Fixed (1 run)

If you want to run this notebook, keep in mind that the library path from the FLORIS config file has to be changed accordingly to your new path

## Imports and environment set up

In [1]:
from pathlib import Path
from itertools import product

import pandas as pd
import matplotlib.pyplot as plt

import numpy as np

from whale import Project
from whale.utilities import load_yaml

pd.options.display.float_format = '{:,.4f}'.format
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

%load_ext autoreload
%autoreload 2

# Function to Extract Results

In [2]:
def extract_results(project_name, config):  # Run the project and clean up the logging
    #project_name = "UMaine_catenary"
    library_path = Path("library").resolve()
    
    metrics_configuration = {
        "# Turbines": {"metric": "n_turbines", "kwargs": {}},
        "Turbine Rating (MW)": {"metric": "turbine_rating", "kwargs": {}},
        "Project Capacity (MW)": {"metric": "capacity", "kwargs": {"units": "mw"}},
        "# OSS": {"metric": "n_substations", "kwargs": {}},
        "Total Export Cable Length (km)": {"metric": "export_system_total_cable_length", "kwargs": {}},
        "Total Array Cable Length (km)": {"metric": "array_system_total_cable_length", "kwargs": {}},
        "CapEx ($)": {"metric": "capex", "kwargs": {}},
        "CapEx per kW ($/kW)": {"metric": "capex", "kwargs": {"per_capacity": "kw"}},
        "OpEx ($)": {"metric": "opex", "kwargs": {}},
        "OpEx per kW ($/kW)": {"metric": "opex", "kwargs": {"per_capacity": "kw"}},
        "AEP (MWh)": {
            "metric": "energy_production",
            "kwargs": {"units": "mw", "aep": True, "with_losses": True}
        },
        "AEP per kW (MWh/kW)": {
            "metric": "energy_production",
            "kwargs": {"units": "mw", "per_capacity": "kw", "aep": True, "with_losses": True}
        },
        "Net Capacity Factor Without Unmodeled Losses (%)": {
            "metric": "capacity_factor",
            "kwargs": {"which": "net"}
        },
        "Net Capacity Factor With All Losses (%)": {
            "metric": "capacity_factor",
            "kwargs": {"which": "net", "with_losses": True}
        },
        "Gross Capacity Factor (%)": {"metric": "capacity_factor", "kwargs": {"which": "gross"}},
        "Energy Availability (%)": {"metric": "availability", "kwargs": {"which": "energy"}},
        "LCOE ($/MWh)": {"metric": "lcoe", "kwargs": {}},
        "IRR (%)": {"metric": "irr", "kwargs": {}},
        "NPV ($)": {"metric": "npv", "kwargs": {}},
    }

    metrics_order = [
        "# Turbines",
        "Turbine Rating (MW)",
        "Project Capacity (MW)",
        "# OSS",
        "Total Export Cable Length (km)",
        "Total Array Cable Length (km)",
        "FCR (%)",
        "Offtake Price ($/MWh)",
        "CapEx ($)",
        "CapEx per kW ($/kW)",
        "System CapEx for Export Cables ($)",
        "Installation CapEx for Export Cables ($)",
        "CapEx Without Export Cables ($)",
        "OpEx ($)",
        "OpEx per kW ($/kW)",
        "Annual OpEx per kW ($/kW)",
        "Energy Availability (%)",
        "Gross Capacity Factor (%)",
        "Net Capacity Factor Without Unmodeled Losses (%)",
        "Net Capacity Factor With All Losses (%)",
        "AEP (MWh)",
        "AEP per kW (MWh/kW)",
        "LCOE ($/MWh)",
        "IRR (%)",
        "NPV ($)",
    ]
    final_cols = ["CapEx ($)", "OpEx ($)", "Energy Production (GWh)", "Revenue ($)", "Cash Flow ($)"]
    
    #config = load_yaml(
        #library_path / "project/config",
        #f"{project_name.replace(' ', '_')}_base.yaml"
    #)

    #wombat_config = load_yaml(
        #library_path / "project/config",
        #f"{project_name.replace(' ', '_')}_base_operations.yaml"
    #)
    
    
    #wombat_config['random_generator'] = np.random.default_rng(seed=34)
    
    #print(wombat_config)
    #config["wombat_config"] = wombat_config
    
    project = Project(
        # Basic Model Configurations
        library_path=library_path,
        #weather_profile=library_path / "weather" / "ocean_wind_1_39.0_-74.0_1959_2023.csv",
        connect_floris_to_layout=True,
        connect_orbit_array_design=True,
        **config,
    )

    
    project.run(
        which_floris="wind_rose",
        full_wind_rose=False,
        floris_reinitialize_kwargs=dict(cut_in_wind_speed=3.0, cut_out_wind_speed=25.0)
    )
    project.wombat.env.cleanup_log_files()  # Delete logging data from WOMBAT
    

    
    #fig, ax = project.plot_farm(return_fig=True)
    #print("Monopile cost and transition piece costs")
    #print(project.orbit.phases['MonopileDesign'].detailed_output)

    df_times = project.wombat.metrics.process_times()

    display(df_times)

    scheduled = project.wombat.metrics.task_completion_rate(which="scheduled", frequency="project").values[0][0]
    unscheduled = project.wombat.metrics.task_completion_rate(which="unscheduled", frequency="project").values[0][0]
    combined = project.wombat.metrics.task_completion_rate(which="both", frequency="project").values[0][0]
    print(f"  Scheduled Task Completion Rate: {scheduled:.2%}")
    print(f"Unscheduled Task Completion Rate: {unscheduled:.2%}")
    print(f"    Overall Task Completion Rate: {combined:.2%}")
 
    df_capex  = pd.DataFrame(project.orbit.capex_breakdown.items(), columns=['CapEx Component', 'Value ($)'])

    df_capex["Value ($/kW)"] = df_capex["Value ($)"]/(project.capacity("mw")*1000)

    #display(df_capex)

    
    df_capex.to_csv('library/results/' + project_name + '_CapEx_Breakdown.csv')
    
    df_opex = project.wombat.metrics.opex(frequency="annual", by_category = True)
    
    #display(df_opex)
    
    df_opex.to_csv('library/results/' + project_name + '_OpEx_Breakdown.csv')
    
    list_of_dict = project.orbit.actions
    df = pd.DataFrame(list_of_dict)
    df.to_csv('library/results/' + project_name + '_Install_Sequence.csv')
    #display(df)
    
    # Gather the high-level results
    report_df = project.generate_report(metrics_configuration, project_name).T
    export_system = project.orbit.system_costs["ExportCableInstallation"]
    export_installation = project.orbit.installation_costs["ExportCableInstallation"]
    capex_sans_export = project.orbit.total_capex - export_system - export_installation
    additional_reporting = pd.DataFrame(
        [
            ["FCR (%)", project.fixed_charge_rate],
            ["Offtake Price ($/MWh)", project.offtake_price],
            ["System CapEx for Export Cables ($)", export_system],
            ["Installation CapEx for Export Cables ($)", export_installation],
            ["CapEx Without Export Cables ($)", capex_sans_export],
            ["Annual OpEx per kW ($/kW)", report_df.loc["OpEx per kW ($/kW)", project_name] / project.operations_years],
        ],
        columns=["Project"] + report_df.columns.tolist(),
    ).set_index("Project")
    report_df = pd.concat((report_df, additional_reporting), axis=0).loc[metrics_order]

    # Gather the detailed results
    monthly_results = project.cash_flow(breakdown=True).join(project.energy_production(frequency="month-year")).fillna(0)
    monthly_results = monthly_results.assign(
        CapEx_Installation=monthly_results[[c for c in monthly_results if c.startswith("CapEx") and c.endswith("Installation")]].sum(axis=1),
        CapEx_System=monthly_results[[c for c in monthly_results if c.startswith("CapEx") and c.endswith("System")]].sum(axis=1),
    )

    # monthly_results.to_csv(library_path / "results" / f"{project_name.lower().replace(' ', '_')}_monthly_detailed_results.csv")
    monthly_results["CapEx ($)"] = monthly_results[["CapEx_Installation", "CapEx_Soft", "CapEx_Project", "CapEx_System", "CapEx_Turbine"]].sum(axis=1)
    monthly_results = monthly_results.rename(columns={"OpEx": "OpEx ($)","Revenue": "Revenue ($)", "cash_flow": "Cash Flow ($)"})[final_cols]

    if "ExportSystemDesign" in project.orbit._phases:
        export = "ExportSystemDesign"
    else:
        export = "ElectricalDesign"

    # Create the inputs data
    inputs = pd.DataFrame(
        [
            ["FCR", project.fixed_charge_rate],
            ["Discount rate (%)", project.discount_rate],
            ["# Turbines", project.n_turbines()],
            ["Turbine Rating (MW)", project.turbine_rating()],
            ["Project Capacity (MW)", project.capacity("mw")],
            ["# OSS", project.n_substations()],
            ["Substructure type", "??"],
            ["Row spacing (rotor diameters)", "not used for custom layouts"],
            ["Turbine spacing (rotor diameters)", "not used for custom layouts"],
            ["Depth (m)", project.orbit.config["site"]["depth"]],
            [
                "Mean wind speed (m/s)",
                project.weather.loc[
                    project.orbit_start_date: project.wombat.env.end_datetime,
                    "windspeed_100m"
                ].mean()
            ],
            ["Distance to landfall (km)", project.orbit.config["site"]["distance_to_landfall"]],
            ["Distance to port (km)", project.wombat.config.port_distance],
            ["Interconnection distance (km)", project.orbit._phases[export]._distance_to_interconnection],
            ["# of POIs", "??"],
            ["Export cable type", [*project.orbit._phases[export].cable_lengths_by_type]],
            ["Array cable type", [*project.orbit._phases["CustomArraySystemDesign"].cable_lengths_by_type]],
        ],
        columns=["Inputs", f"{project_name}"]
    ).set_index("Inputs")

    # Save the outputs
    report_df.index.name = "Metrics"
    wrong_indexes = ["Offtake Price ($/MWh)", "System CapEx for Export Cables ($)", "Installation CapEx for Export Cables ($)", "CapEx Without Export Cables ($)", "IRR (%)", "NPV ($)"]
    
    
    return report_df.drop(wrong_indexes,axis=0)

# Extract CapEx, OpEx, and AEP Outputs - Multiple Runs
Availability and OpEx varies depending on the run as it uses probabilistic functions, so we collect the data from x runs and calculate the average OpEx and AEP

In [3]:
def display_results_all_runs(list_projects):
    import pandas as pd
    library_path = Path("library").resolve()
    df_list_fixed_bottom = list()
    df_list_floating = list()
    df_final_list = list()
    num = 0
    for i in list_projects:
        config = load_yaml(
            library_path / "project/config",
            f"{i.replace(' ', '_')}_base.yaml"
        )

        wombat_config = load_yaml(
            library_path / "project/config",
            f"{i.replace(' ', '_')}_base_operations.yaml"
        )
    
    
        wombat_config['random_generator'] = np.random.default_rng(seed=34)
    
        print(wombat_config)
        config["wombat_config"] = wombat_config
        for j in range(0,1):
            
            df_2 = extract_results(i, config)
            
            if num == 0:
                df_list_floating = df_2
            else:
                df_list_floating = pd.concat([df_list_floating, df_2], axis=1)
                display(df_list_floating)
            
            num = num + 1        

            
    final_df = df_list_floating
                          
    return final_df

In [4]:
import time
t1 = time.perf_counter()

list_projects_15_MW = ["fixed_bottom_15_MW_-10%", "fixed_bottom_15_MW_-5%", "fixed_bottom_15_MW_baseline"]
summary_results = display_results_all_runs(list_projects_15_MW)

t2 = time.perf_counter()
print('time taken to run:',t2-t1)

{'name': 'fixed_bottom_15_MW_-10%_fixed_bottom', 'library': 'library', 'weather': 'boem_era5_41.0_-70.5.csv', 'service_equipment': ['ctv1.yaml', 'ctv2.yaml', 'ctv3.yaml', 'clv.yaml', 'jackup.yaml', 'dsv.yaml'], 'layout': 'fixed_bottom_layout_15_MW_-10%.csv', 'inflation_rate': 0, 'fixed_costs': 'fixed_bottom_fixed_costs.yaml', 'workday_start': 7, 'workday_end': 19, 'start_year': 2000, 'end_year': 2020, 'project_capacity': 600, 'port': 'port116.yaml', 'random_generator': Generator(PCG64) at 0x2759F722EA0}
ORBIT library intialized at 'C:\upsizing\WHaLE\examples\library'

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"472,647.8185","51,538.0433","66,690.2016","422,807.1455",813
annual turbine inspection,"411,615.7768","52,385.0533","63,925.7838","360,880.2662",830
cable major repair,"18,570.8695","11,366.4014",0.0000,"7,285.5439",21
cable replacement,"24,841.9109","17,360.8987",0.0000,"7,534.1609",20
inspection,"31,894.2584",316.3979,0.0000,"31,610.7584",10
main shaft major repair,"1,896.0713","1,685.8569","1,705.2425",268.3213,17
main shaft minor repair,"6,586.3096","3,665.5071","4,449.7793","3,232.5596",168
main shaft replacement,"8,534.9010","1,620.5272","8,534.9010","6,933.1001",6
major pitch system repair,"13,655.3076","11,950.8297","12,068.3193","1,986.0576",123
major pitch system replacement,"3,817.1080",508.7229,"3,817.1080","3,321.7716",5
major repair,"6,746.7450","5,447.3344","5,537.6335","1,045.8563",57
major replacement,"14,697.2207","3,767.5921","14,697.2207","10,935.5013",9
marine growth removal,"9,453.5586","7,946.7386","7,909.5552","1,688.5948",79
minor ballast pump repair,125.1591,96.6197,83.4983,51.6591,4
minor pitch system repair,"42,309.1597","28,832.5303","31,376.7330","14,622.6605",652
minor repair,"67,992.3005","40,886.3723","46,696.0403","28,226.0856",1385
power converter major repair,"46,877.1481","36,552.9297","37,314.0737","8,679.4559",516
power converter minor repair,"45,819.7968","27,189.9017","28,476.8881","17,104.3397",769
power converter replacement,"193,872.0321","35,199.2138","191,789.5821","157,492.8304",122
subsea inspection,"303,933.0409","5,636.8466","24,600.9008","298,941.5403",393

  Scheduled Task Completion Rate: 99.61%
Unscheduled Task Completion Rate: 99.44%
    Overall Task Completion Rate: 99.50%
{'name': 'fixed_bottom_15_MW_-5%_fixed_bottom', 'library': 'library', 'weather': 'boem_era5_41.0_-70.5.csv', 'service_equipment': ['ctv1.yaml', 'ctv2.yaml', 'ctv3.yaml', 'clv.yaml', 'jackup.yaml', 'dsv.yaml'], 'layout': 'fixed_bottom_layout_15_MW_-5%.csv', 'inflation_rate': 0, 'fixed_costs': 'fixed_bottom_fixed_costs.yaml', 'workday_start': 7, 'workday_end': 19, 'start_year': 2000, 'end_year': 2020, 'project_capacity': 600, 'port': 'port116.yaml', 'random_generator': Generator(PCG64) at 0x275A9E2CAC0}

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"424,684.6329","50,718.3774","72,131.2383","375,572.3829",807
annual turbine inspection,"369,214.0547","53,073.5227","67,077.3157","315,319.9368",828
cable major repair,"17,511.3414","10,545.0408",0.0000,"7,023.3414",18
cable replacement,"17,844.8569","12,804.7097",0.0000,"5,120.6069",16
inspection,"33,404.4447",288.1001,0.0000,"33,134.4447",10
main shaft major repair,"2,108.7404","1,869.5788","1,865.7483",274.9904,20
main shaft minor repair,"6,219.6747","3,867.7694","3,913.7660","2,708.6747",177
main shaft replacement,"6,666.5828","1,587.9047","6,666.5828","5,123.1962",6
major pitch system repair,"18,603.9213","15,616.5076","16,710.7586","3,223.1713",162
major pitch system replacement,"5,209.2922",482.0032,"5,209.2922","4,730.3031",5
major repair,"6,584.0507","5,901.7017","5,969.0207",755.5507,58
major replacement,"16,518.0433","4,562.9019","16,518.0433","12,096.6005",11
marine growth removal,"11,831.3177","9,484.6911","9,720.3995","2,506.8496",97
minor ballast pump repair,164.9301,78.2597,146.8303,88.4301,6
minor pitch system repair,"46,487.2408","31,427.8601","34,613.7669","16,389.7795",686
minor repair,"74,479.8773","46,413.7270","50,633.7052","28,943.9396",1525
power converter major repair,"54,336.0003","42,464.0966","44,288.7170","10,486.6629",595
power converter minor repair,"59,042.2007","33,516.6160","38,286.1374","23,578.4585",924
power converter replacement,"207,920.5893","36,834.5524","202,356.0547","166,411.1405",142
subsea inspection,"262,593.6104","5,371.6349","52,944.1468","257,818.6104",387

  Scheduled Task Completion Rate: 99.75%
Unscheduled Task Completion Rate: 99.48%
    Overall Task Completion Rate: 99.57%

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-5%
Metrics,,
# Turbines,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000
Project Capacity (MW),600.0000,600.0000
# OSS,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491
FCR (%),0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,163,582,929.2763"
OpEx per kW ($/kW),"1,892.4047","1,939.3049"
Annual OpEx per kW ($/kW),90.1145,92.3479
Energy Availability (%),0.9478,0.9429
Gross Capacity Factor (%),0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5135
Net Capacity Factor With All Losses (%),0.4618,0.4596
AEP (MWh),"2,429,136.0555","2,417,313.9168"
AEP per kW (MWh/kW),4.0486,4.0289
LCOE ($/MWh),83.6746,84.6382

{'name': 'fixed_bottom_15_MW_baseline_fixed_bottom', 'library': 'library', 'weather': 'boem_era5_41.0_-70.5.csv', 'service_equipment': ['ctv1.yaml', 'ctv2.yaml', 'ctv3.yaml', 'clv.yaml', 'jackup.yaml', 'dsv.yaml'], 'layout': 'fixed_bottom_layout_15_MW_baseline.csv', 'inflation_rate': 0, 'fixed_costs': 'fixed_bottom_fixed_costs.yaml', 'workday_start': 7, 'workday_end': 19, 'start_year': 2000, 'end_year': 2020, 'project_capacity': 600, 'port': 'port116.yaml', 'random_generator': Generator(PCG64) at 0x275A9E2FA00}

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"463,172.0949","51,456.4664","82,751.1677","413,389.9641",806
annual turbine inspection,"414,820.6854","53,203.2787","80,131.6395","363,353.3574",843
cable major repair,"18,608.2945","11,122.7040",0.0000,"6,613.5558",20
cable replacement,"21,044.2736","14,502.8589",0.0000,"6,582.2736",17
inspection,"33,910.4301",305.7943,0.0000,"33,626.9301",10
main shaft major repair,"2,503.3176","2,250.0131","2,233.2103",361.3176,23
main shaft minor repair,"8,424.4475","3,762.6854","5,731.0012","4,989.6592",182
main shaft replacement,"4,113.9780","1,065.6028","4,113.9780","3,059.4780",4
major pitch system repair,"19,013.7282","15,979.0826","16,883.5278","3,222.7279",159
major pitch system replacement,"6,876.4210",651.5680,"6,876.4210","6,339.1710",5
major repair,"6,805.8942","5,804.6659","5,922.7200",938.0742,61
major replacement,"19,536.2927","5,348.4734","19,536.2927","14,350.0427",12
marine growth removal,"11,764.7392","9,482.8226","9,833.2875","2,414.8742",93
minor ballast pump repair,291.8902,124.7354,124.4992,180.1402,7
minor pitch system repair,"51,370.1504","31,118.2919","35,633.8599","21,454.7660",699
minor repair,"85,224.1121","51,105.0768","55,491.0409","34,551.6170",1646
power converter major repair,"57,185.4418","44,818.7746","46,050.1935","10,693.6705",631
power converter minor repair,"75,859.1090","36,330.0233","41,224.3298","30,824.1249",997
power converter replacement,"213,947.1427","38,558.0382","211,366.6284","173,970.6714",148
subsea inspection,"347,906.3095","5,561.1068","52,079.2923","343,104.8095",386

  Scheduled Task Completion Rate: 99.56%
Unscheduled Task Completion Rate: 99.43%
    Overall Task Completion Rate: 99.47%

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-5%,fixed_bottom_15_MW_baseline
Metrics,,,
# Turbines,40.0000,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000,15.0000
Project Capacity (MW),600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491,196.5491
FCR (%),0.0648,0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,163,582,929.2763","1,200,571,302.9544"
OpEx per kW ($/kW),"1,892.4047","1,939.3049","2,000.9522"
Annual OpEx per kW ($/kW),90.1145,92.3479,95.2834
Energy Availability (%),0.9478,0.9429,0.9402
Gross Capacity Factor (%),0.5392,0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5135,0.5123
Net Capacity Factor With All Losses (%),0.4618,0.4596,0.4584
AEP (MWh),"2,429,136.0555","2,417,313.9168","2,411,012.0855"
AEP per kW (MWh/kW),4.0486,4.0289,4.0184
LCOE ($/MWh),83.6746,84.6382,85.5899

time taken to run: 1041.2302518999786

In [5]:
display(summary_results)

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-5%,fixed_bottom_15_MW_baseline
Metrics,,,
# Turbines,40.0000,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000,15.0000
Project Capacity (MW),600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491,196.5491
FCR (%),0.0648,0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,163,582,929.2763","1,200,571,302.9544"
OpEx per kW ($/kW),"1,892.4047","1,939.3049","2,000.9522"
Annual OpEx per kW ($/kW),90.1145,92.3479,95.2834
Energy Availability (%),0.9478,0.9429,0.9402
Gross Capacity Factor (%),0.5392,0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5135,0.5123
Net Capacity Factor With All Losses (%),0.4618,0.4596,0.4584
AEP (MWh),"2,429,136.0555","2,417,313.9168","2,411,012.0855"
AEP per kW (MWh/kW),4.0486,4.0289,4.0184
LCOE ($/MWh),83.6746,84.6382,85.5899

In [6]:
summary_results.to_csv('library/results/task_completion_15_MW_LCOE_Breakdown.csv')

In [7]:
def display_results_all_runs_2(list_projects):
    import pandas as pd
    library_path = Path("library").resolve()
    df_list_fixed_bottom = list()
    df_list_floating = list()
    df_final_list = list()
    num = 0
    for i in list_projects:
        config = load_yaml(
            library_path / "project/config",
            f"{i.replace(' ', '_')}_base.yaml"
        )

        wombat_config = load_yaml(
            library_path / "project/config",
            f"{i.replace(' ', '_')}_base_operations.yaml"
        )
    
    
        wombat_config['random_generator'] = np.random.default_rng(seed=34)
    
        print(wombat_config)
        config["wombat_config"] = wombat_config
        for j in range(0,2):
            
            df_2 = extract_results(i, config)
            
            if num == 0:
                df_list_floating = df_2
            else:
                df_list_floating = pd.concat([df_list_floating, df_2], axis=1)
                display(df_list_floating)
            
            num = num + 1        

            
    final_df = df_list_floating
                          
    return final_df

In [8]:
import time
t1 = time.perf_counter()

list_projects_15_MW = ["fixed_bottom_15_MW_-10%", "fixed_bottom_15_MW_-5%", "fixed_bottom_15_MW_baseline"]
summary_results = display_results_all_runs_2(list_projects_15_MW)

t2 = time.perf_counter()
print('time taken to run:',t2-t1)

{'name': 'fixed_bottom_15_MW_-10%_fixed_bottom', 'library': 'library', 'weather': 'boem_era5_41.0_-70.5.csv', 'service_equipment': ['ctv1.yaml', 'ctv2.yaml', 'ctv3.yaml', 'clv.yaml', 'jackup.yaml', 'dsv.yaml'], 'layout': 'fixed_bottom_layout_15_MW_-10%.csv', 'inflation_rate': 0, 'fixed_costs': 'fixed_bottom_fixed_costs.yaml', 'workday_start': 7, 'workday_end': 19, 'start_year': 2000, 'end_year': 2020, 'project_capacity': 600, 'port': 'port116.yaml', 'random_generator': Generator(PCG64) at 0x275A1FDA260}

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"472,647.8185","51,538.0433","66,690.2016","422,807.1455",813
annual turbine inspection,"411,615.7768","52,385.0533","63,925.7838","360,880.2662",830
cable major repair,"18,570.8695","11,366.4014",0.0000,"7,285.5439",21
cable replacement,"24,841.9109","17,360.8987",0.0000,"7,534.1609",20
inspection,"31,894.2584",316.3979,0.0000,"31,610.7584",10
main shaft major repair,"1,896.0713","1,685.8569","1,705.2425",268.3213,17
main shaft minor repair,"6,586.3096","3,665.5071","4,449.7793","3,232.5596",168
main shaft replacement,"8,534.9010","1,620.5272","8,534.9010","6,933.1001",6
major pitch system repair,"13,655.3076","11,950.8297","12,068.3193","1,986.0576",123
major pitch system replacement,"3,817.1080",508.7229,"3,817.1080","3,321.7716",5
major repair,"6,746.7450","5,447.3344","5,537.6335","1,045.8563",57
major replacement,"14,697.2207","3,767.5921","14,697.2207","10,935.5013",9
marine growth removal,"9,453.5586","7,946.7386","7,909.5552","1,688.5948",79
minor ballast pump repair,125.1591,96.6197,83.4983,51.6591,4
minor pitch system repair,"42,309.1597","28,832.5303","31,376.7330","14,622.6605",652
minor repair,"67,992.3005","40,886.3723","46,696.0403","28,226.0856",1385
power converter major repair,"46,877.1481","36,552.9297","37,314.0737","8,679.4559",516
power converter minor repair,"45,819.7968","27,189.9017","28,476.8881","17,104.3397",769
power converter replacement,"193,872.0321","35,199.2138","191,789.5821","157,492.8304",122
subsea inspection,"303,933.0409","5,636.8466","24,600.9008","298,941.5403",393

  Scheduled Task Completion Rate: 99.61%
Unscheduled Task Completion Rate: 99.44%
    Overall Task Completion Rate: 99.50%

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"429,127.5584","51,258.6185","62,469.6819","379,519.1056",811
annual turbine inspection,"373,281.6880","51,313.9873","60,775.5303","323,744.4389",819
cable major repair,"23,509.4584","13,524.0353",0.0000,"10,078.2084",26
cable replacement,"16,353.5763","11,959.4140",0.0000,"4,473.5763",14
inspection,"32,729.2949",265.5517,0.0000,"32,487.2949",10
main shaft major repair,714.5323,669.9670,669.4981,58.0323,8
main shaft minor repair,"5,500.8036","3,268.3339","3,248.4955","2,519.0536",164
main shaft replacement,"7,044.2531","1,833.7295","7,044.2531","5,262.7531",8
major pitch system repair,"14,717.8188","13,237.2727","13,227.9707","1,696.8188",138
major repair,"8,169.0540","7,289.2738","7,355.5685","1,071.8040",70
major replacement,"4,722.3947","3,075.4978","4,722.3947","1,649.8486",6
marine growth removal,"9,216.7710","7,882.2538","7,894.1974","1,465.0210",78
minor ballast pump repair,179.2287,148.5002,146.0000,35.2287,8
minor pitch system repair,"41,384.9063","28,092.8930","29,832.7616","14,514.7888",640
minor repair,"67,550.3225","42,419.1691","45,833.1008","26,764.9959",1421
power converter major repair,"41,486.1471","34,297.3521","35,647.9820","7,858.1441",477
power converter minor repair,"45,620.8843","28,937.0283","30,209.6280","16,311.0180",789
power converter replacement,"178,177.0101","28,553.2426","177,567.5592","149,479.2745",94
subsea inspection,"234,793.7462","5,425.1725","23,887.9251","229,922.7462",391

  Scheduled Task Completion Rate: 99.61%
Unscheduled Task Completion Rate: 99.80%
    Overall Task Completion Rate: 99.73%

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-10%
Metrics,,
# Turbines,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000
Project Capacity (MW),600.0000,600.0000
# OSS,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491
FCR (%),0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,013,087,096.2126"
OpEx per kW ($/kW),"1,892.4047","1,688.4785"
Annual OpEx per kW ($/kW),90.1145,80.4037
Energy Availability (%),0.9478,0.9504
Gross Capacity Factor (%),0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5166
Net Capacity Factor With All Losses (%),0.4618,0.4627
AEP (MWh),"2,429,136.0555","2,433,966.0402"
AEP per kW (MWh/kW),4.0486,4.0566
LCOE ($/MWh),83.6746,81.1148

{'name': 'fixed_bottom_15_MW_-5%_fixed_bottom', 'library': 'library', 'weather': 'boem_era5_41.0_-70.5.csv', 'service_equipment': ['ctv1.yaml', 'ctv2.yaml', 'ctv3.yaml', 'clv.yaml', 'jackup.yaml', 'dsv.yaml'], 'layout': 'fixed_bottom_layout_15_MW_-5%.csv', 'inflation_rate': 0, 'fixed_costs': 'fixed_bottom_fixed_costs.yaml', 'workday_start': 7, 'workday_end': 19, 'start_year': 2000, 'end_year': 2020, 'project_capacity': 600, 'port': 'port116.yaml', 'random_generator': Generator(PCG64) at 0x275ACB05E00}

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"424,684.6329","50,718.3774","72,131.2383","375,572.3829",807
annual turbine inspection,"369,214.0547","53,073.5227","67,077.3157","315,319.9368",828
cable major repair,"17,511.3414","10,545.0408",0.0000,"7,023.3414",18
cable replacement,"17,844.8569","12,804.7097",0.0000,"5,120.6069",16
inspection,"33,404.4447",288.1001,0.0000,"33,134.4447",10
main shaft major repair,"2,108.7404","1,869.5788","1,865.7483",274.9904,20
main shaft minor repair,"6,219.6747","3,867.7694","3,913.7660","2,708.6747",177
main shaft replacement,"6,666.5828","1,587.9047","6,666.5828","5,123.1962",6
major pitch system repair,"18,603.9213","15,616.5076","16,710.7586","3,223.1713",162
major pitch system replacement,"5,209.2922",482.0032,"5,209.2922","4,730.3031",5
major repair,"6,584.0507","5,901.7017","5,969.0207",755.5507,58
major replacement,"16,518.0433","4,562.9019","16,518.0433","12,096.6005",11
marine growth removal,"11,831.3177","9,484.6911","9,720.3995","2,506.8496",97
minor ballast pump repair,164.9301,78.2597,146.8303,88.4301,6
minor pitch system repair,"46,487.2408","31,427.8601","34,613.7669","16,389.7795",686
minor repair,"74,479.8773","46,413.7270","50,633.7052","28,943.9396",1525
power converter major repair,"54,336.0003","42,464.0966","44,288.7170","10,486.6629",595
power converter minor repair,"59,042.2007","33,516.6160","38,286.1374","23,578.4585",924
power converter replacement,"207,920.5893","36,834.5524","202,356.0547","166,411.1405",142
subsea inspection,"262,593.6104","5,371.6349","52,944.1468","257,818.6104",387

  Scheduled Task Completion Rate: 99.75%
Unscheduled Task Completion Rate: 99.48%
    Overall Task Completion Rate: 99.57%

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-5%
Metrics,,,
# Turbines,40.0000,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000,15.0000
Project Capacity (MW),600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491,196.5491
FCR (%),0.0648,0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,013,087,096.2126","1,163,582,929.2763"
OpEx per kW ($/kW),"1,892.4047","1,688.4785","1,939.3049"
Annual OpEx per kW ($/kW),90.1145,80.4037,92.3479
Energy Availability (%),0.9478,0.9504,0.9429
Gross Capacity Factor (%),0.5392,0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5166,0.5135
Net Capacity Factor With All Losses (%),0.4618,0.4627,0.4596
AEP (MWh),"2,429,136.0555","2,433,966.0402","2,417,313.9168"
AEP per kW (MWh/kW),4.0486,4.0566,4.0289
LCOE ($/MWh),83.6746,81.1148,84.6382

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"396,361.3185","51,227.5416","76,655.4208","346,835.4110",807
annual turbine inspection,"334,431.8984","54,368.8307","74,323.3733","281,831.0253",841
cable major repair,"29,395.2138","17,432.9374",0.0000,"12,041.7138",32
cable replacement,"13,295.0939","9,598.9975",0.0000,"3,757.5939",11
inspection,"33,697.5340",377.0836,0.0000,"33,343.7837",10
main shaft major repair,"1,523.0990","1,363.9675","1,368.3666",190.0990,14
main shaft minor repair,"6,087.4641","3,668.3821","3,656.9737","2,790.2141",182
main shaft replacement,"5,571.3761","2,357.6032","5,571.3761","3,283.8363",7
major pitch system repair,"15,359.8866","12,926.9265","13,732.7634","2,665.1366",135
major repair,"7,308.5546","6,584.2068","6,585.9189",805.5546,62
major replacement,"10,901.8528","2,550.4021","10,901.8528","8,604.8528",12
marine growth removal,"13,331.0653","10,923.4296","11,452.5224","2,506.0511",106
minor ballast pump repair,209.5826,133.6739,132.2478,81.5826,5
minor pitch system repair,"38,226.8518","26,064.5715","27,628.5608","13,170.8518",607
minor repair,"69,445.0937","43,423.1781","46,580.8712","25,386.8705",1443
power converter major repair,"50,762.7549","40,590.3150","41,473.3300","8,861.6726",582
power converter minor repair,"58,223.4967","34,020.4921","36,469.8321","20,684.2854",943
power converter replacement,"196,150.7750","36,715.7838","190,844.1108","155,027.5455",132
subsea inspection,"290,912.5876","5,544.1674","33,636.4340","286,041.5876",387

  Scheduled Task Completion Rate: 99.95%
Unscheduled Task Completion Rate: 99.51%
    Overall Task Completion Rate: 99.65%

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-5%,fixed_bottom_15_MW_-5%
Metrics,,,,
# Turbines,40.0000,40.0000,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000,15.0000,15.0000
Project Capacity (MW),600.0000,600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491,196.5491,196.5491
FCR (%),0.0648,0.0648,0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480","3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,013,087,096.2126","1,163,582,929.2763","1,147,556,090.8469"
OpEx per kW ($/kW),"1,892.4047","1,688.4785","1,939.3049","1,912.5935"
Annual OpEx per kW ($/kW),90.1145,80.4037,92.3479,91.0759
Energy Availability (%),0.9478,0.9504,0.9429,0.9413
Gross Capacity Factor (%),0.5392,0.5392,0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5166,0.5135,0.5142
Net Capacity Factor With All Losses (%),0.4618,0.4627,0.4596,0.4603
AEP (MWh),"2,429,136.0555","2,433,966.0402","2,417,313.9168","2,421,265.6549"
AEP per kW (MWh/kW),4.0486,4.0566,4.0289,4.0354
LCOE ($/MWh),83.6746,81.1148,84.6382,84.1848

{'name': 'fixed_bottom_15_MW_baseline_fixed_bottom', 'library': 'library', 'weather': 'boem_era5_41.0_-70.5.csv', 'service_equipment': ['ctv1.yaml', 'ctv2.yaml', 'ctv3.yaml', 'clv.yaml', 'jackup.yaml', 'dsv.yaml'], 'layout': 'fixed_bottom_layout_15_MW_baseline.csv', 'inflation_rate': 0, 'fixed_costs': 'fixed_bottom_fixed_costs.yaml', 'workday_start': 7, 'workday_end': 19, 'start_year': 2000, 'end_year': 2020, 'project_capacity': 600, 'port': 'port116.yaml', 'random_generator': Generator(PCG64) at 0x275B7C05380}

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"463,172.0949","51,456.4664","82,751.1677","413,389.9641",806
annual turbine inspection,"414,820.6854","53,203.2787","80,131.6395","363,353.3574",843
cable major repair,"18,608.2945","11,122.7040",0.0000,"6,613.5558",20
cable replacement,"21,044.2736","14,502.8589",0.0000,"6,582.2736",17
inspection,"33,910.4301",305.7943,0.0000,"33,626.9301",10
main shaft major repair,"2,503.3176","2,250.0131","2,233.2103",361.3176,23
main shaft minor repair,"8,424.4475","3,762.6854","5,731.0012","4,989.6592",182
main shaft replacement,"4,113.9780","1,065.6028","4,113.9780","3,059.4780",4
major pitch system repair,"19,013.7282","15,979.0826","16,883.5278","3,222.7279",159
major pitch system replacement,"6,876.4210",651.5680,"6,876.4210","6,339.1710",5
major repair,"6,805.8942","5,804.6659","5,922.7200",938.0742,61
major replacement,"19,536.2927","5,348.4734","19,536.2927","14,350.0427",12
marine growth removal,"11,764.7392","9,482.8226","9,833.2875","2,414.8742",93
minor ballast pump repair,291.8902,124.7354,124.4992,180.1402,7
minor pitch system repair,"51,370.1504","31,118.2919","35,633.8599","21,454.7660",699
minor repair,"85,224.1121","51,105.0768","55,491.0409","34,551.6170",1646
power converter major repair,"57,185.4418","44,818.7746","46,050.1935","10,693.6705",631
power converter minor repair,"75,859.1090","36,330.0233","41,224.3298","30,824.1249",997
power converter replacement,"213,947.1427","38,558.0382","211,366.6284","173,970.6714",148
subsea inspection,"347,906.3095","5,561.1068","52,079.2923","343,104.8095",386

  Scheduled Task Completion Rate: 99.56%
Unscheduled Task Completion Rate: 99.43%
    Overall Task Completion Rate: 99.47%

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-5%,fixed_bottom_15_MW_-5%,fixed_bottom_15_MW_baseline
Metrics,,,,,
# Turbines,40.0000,40.0000,40.0000,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000,15.0000,15.0000,15.0000
Project Capacity (MW),600.0000,600.0000,600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680,118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491,196.5491,196.5491,196.5491
FCR (%),0.0648,0.0648,0.0648,0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480","3,837.1480","3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,013,087,096.2126","1,163,582,929.2763","1,147,556,090.8469","1,200,571,302.9544"
OpEx per kW ($/kW),"1,892.4047","1,688.4785","1,939.3049","1,912.5935","2,000.9522"
Annual OpEx per kW ($/kW),90.1145,80.4037,92.3479,91.0759,95.2834
Energy Availability (%),0.9478,0.9504,0.9429,0.9413,0.9402
Gross Capacity Factor (%),0.5392,0.5392,0.5392,0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5166,0.5135,0.5142,0.5123
Net Capacity Factor With All Losses (%),0.4618,0.4627,0.4596,0.4603,0.4584
AEP (MWh),"2,429,136.0555","2,433,966.0402","2,417,313.9168","2,421,265.6549","2,411,012.0855"
AEP per kW (MWh/kW),4.0486,4.0566,4.0289,4.0354,4.0184
LCOE ($/MWh),83.6746,81.1148,84.6382,84.1848,85.5899

UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\upsizing\ORBIT\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,time_to_completion,process_time,downtime,time_to_start,N
category,,,,,
annual inspection,"477,539.4350","51,539.3827","68,442.6385","427,856.9350",808
annual turbine inspection,"404,875.4818","55,286.6992","65,811.4827","350,693.1911",859
cable major repair,"23,147.4897","14,074.2039",0.0000,"9,152.4897",24
cable replacement,"23,031.7527","16,554.9846",0.0000,"6,541.0027",19
inspection,"33,533.0419",282.7975,0.0000,"33,277.5419",10
main shaft major repair,"2,646.4878","2,334.8568","2,406.3297",399.2378,24
main shaft minor repair,"7,034.8251","4,240.0647","4,449.9714","3,179.3251",190
main shaft replacement,"7,442.3867","2,656.6133","7,442.3867","5,076.6367",10
major pitch system repair,"15,152.8080","13,467.0530","13,648.4038","1,790.3080",140
major repair,"7,640.1286","6,821.6529","6,864.9924",966.3786,69
major replacement,"14,722.1303","2,877.2556","14,722.1303","11,927.7678",12
marine growth removal,"12,036.9120","9,280.1778","10,377.2656","2,873.6620",91
minor ballast pump repair,148.2816,73.2469,73.0000,77.0316,7
minor pitch system repair,"40,218.7278","27,968.4761","29,663.9969","13,589.2278",619
minor repair,"79,306.5594","48,461.2179","54,603.5627","31,995.6633",1610
power converter major repair,"51,318.5653","41,701.3752","43,067.2811","9,722.9495",583
power converter minor repair,"67,802.8754","37,064.9788","39,987.0630","27,500.9468",1010
power converter replacement,"214,150.3064","37,825.3070","206,920.9060","170,006.5710",151
subsea inspection,"434,426.2873","5,469.2307","61,715.5643","429,450.7873",389

  Scheduled Task Completion Rate: 99.81%
Unscheduled Task Completion Rate: 99.36%
    Overall Task Completion Rate: 99.50%

,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-10%,fixed_bottom_15_MW_-5%,fixed_bottom_15_MW_-5%,fixed_bottom_15_MW_baseline,fixed_bottom_15_MW_baseline
Metrics,,,,,,
# Turbines,40.0000,40.0000,40.0000,40.0000,40.0000,40.0000
Turbine Rating (MW),15.0000,15.0000,15.0000,15.0000,15.0000,15.0000
Project Capacity (MW),600.0000,600.0000,600.0000,600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680,118.0680,118.0680,118.0680
Total Array Cable Length (km),196.5491,196.5491,196.5491,196.5491,196.5491,196.5491
FCR (%),0.0648,0.0648,0.0648,0.0648,0.0648,0.0648
CapEx ($),"2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287","2,302,288,824.0287"
CapEx per kW ($/kW),"3,837.1480","3,837.1480","3,837.1480","3,837.1480","3,837.1480","3,837.1480"
OpEx ($),"1,135,442,837.4601","1,013,087,096.2126","1,163,582,929.2763","1,147,556,090.8469","1,200,571,302.9544","1,180,845,925.9376"
OpEx per kW ($/kW),"1,892.4047","1,688.4785","1,939.3049","1,912.5935","2,000.9522","1,968.0765"
Annual OpEx per kW ($/kW),90.1145,80.4037,92.3479,91.0759,95.2834,93.7179
Energy Availability (%),0.9478,0.9504,0.9429,0.9413,0.9402,0.9404
Gross Capacity Factor (%),0.5392,0.5392,0.5392,0.5392,0.5392,0.5392
Net Capacity Factor Without Unmodeled Losses (%),0.5157,0.5166,0.5135,0.5142,0.5123,0.5132
Net Capacity Factor With All Losses (%),0.4618,0.4627,0.4596,0.4603,0.4584,0.4593
AEP (MWh),"2,429,136.0555","2,433,966.0402","2,417,313.9168","2,421,265.6549","2,411,012.0855","2,416,025.3608"
AEP per kW (MWh/kW),4.0486,4.0566,4.0289,4.0354,4.0184,4.0267
LCOE ($/MWh),83.6746,81.1148,84.6382,84.1848,85.5899,85.0236

time taken to run: 2236.8749993999954