# 2022 COE Review AEP Weather Benchmark Working Analysis

If you want to run this notebook, keep in mind that the library path from the FLORIS config file has to be changed accordingly to your new path

## Imports and environment set up

In [1]:
from pathlib import Path
from itertools import product

import pandas as pd
import matplotlib.pyplot as plt

from whale import Project
from whale.utilities import load_yaml

pd.options.display.float_format = '{:,.4f}'.format
pd.options.display.max_columns = 100
pd.options.display.max_rows = 100

%load_ext autoreload
%autoreload 2

# Function to Extract Results

In [2]:
def extract_results(project_name):  # Run the project and clean up the logging
    #project_name = "UMaine_catenary"
    library_path = Path("library").resolve()
    
    metrics_configuration = {
        "# Turbines": {"metric": "n_turbines", "kwargs": {}},
        "Turbine Rating (MW)": {"metric": "turbine_rating", "kwargs": {}},
        "Project Capacity (MW)": {"metric": "capacity", "kwargs": {"units": "mw"}},
        "# OSS": {"metric": "n_substations", "kwargs": {}},
        "Total Export Cable Length (km)": {"metric": "export_system_total_cable_length", "kwargs": {}},
        "Total Array Cable Length (km)": {"metric": "array_system_total_cable_length", "kwargs": {}},
        "CapEx ($)": {"metric": "capex", "kwargs": {}},
        "CapEx per kW ($/kW)": {"metric": "capex", "kwargs": {"per_capacity": "kw"}},
        "OpEx ($)": {"metric": "opex", "kwargs": {}},
        "OpEx per kW ($/kW)": {"metric": "opex", "kwargs": {"per_capacity": "kw"}},
        "AEP (MWh)": {
            "metric": "energy_production",
            "kwargs": {"units": "mw", "aep": True, "with_losses": True}
        },
        "AEP per kW (MWh/kW)": {
            "metric": "energy_production",
            "kwargs": {"units": "mw", "per_capacity": "kw", "aep": True, "with_losses": True}
        },
        "Net Capacity Factor Without Unmodeled Losses (%)": {
            "metric": "capacity_factor",
            "kwargs": {"which": "net"}
        },
        "Net Capacity Factor With All Losses (%)": {
            "metric": "capacity_factor",
            "kwargs": {"which": "net", "with_losses": True}
        },
        "Gross Capacity Factor (%)": {"metric": "capacity_factor", "kwargs": {"which": "gross"}},
        "Energy Availability (%)": {"metric": "availability", "kwargs": {"which": "energy"}},
        "LCOE ($/MWh)": {"metric": "lcoe", "kwargs": {}},
        "IRR (%)": {"metric": "irr", "kwargs": {}},
        "NPV ($)": {"metric": "npv", "kwargs": {}},
    }

    metrics_order = [
        "# Turbines",
        "Turbine Rating (MW)",
        "Project Capacity (MW)",
        "# OSS",
        "Total Export Cable Length (km)",
        "Total Array Cable Length (km)",
        "FCR (%)",
        "Offtake Price ($/MWh)",
        "CapEx ($)",
        "CapEx per kW ($/kW)",
        "System CapEx for Export Cables ($)",
        "Installation CapEx for Export Cables ($)",
        "CapEx Without Export Cables ($)",
        "OpEx ($)",
        "OpEx per kW ($/kW)",
        "Annual OpEx per kW ($/kW)",
        "Energy Availability (%)",
        "Gross Capacity Factor (%)",
        "Net Capacity Factor Without Unmodeled Losses (%)",
        "Net Capacity Factor With All Losses (%)",
        "AEP (MWh)",
        "AEP per kW (MWh/kW)",
        "LCOE ($/MWh)",
        "IRR (%)",
        "NPV ($)",
    ]
    final_cols = ["CapEx ($)", "OpEx ($)", "Energy Production (GWh)", "Revenue ($)", "Cash Flow ($)"]
    
    config = load_yaml(
        library_path / "project/config",
        f"{project_name.replace(' ', '_')}_base.yaml"
    )
    project = Project(
        # Basic Model Configurations
        library_path=library_path,
        #weather_profile=library_path / "weather" / "ocean_wind_1_39.0_-74.0_1959_2023.csv",
        connect_floris_to_layout=True,
        connect_orbit_array_design=True,
        **config,
    )

    
    project.run(
        which_floris="wind_rose",
        full_wind_rose=False,
        floris_reinitialize_kwargs=dict(cut_in_wind_speed=3.0, cut_out_wind_speed=25.0)
    )
    project.wombat.env.cleanup_log_files()  # Delete logging data from WOMBAT
    
    #fig, ax = project.plot_farm(return_fig=True)
    df_opex = project.wombat.metrics.opex(frequency="annual", by_category = True)
    
    display(df_opex)
    
    df_opex.to_csv('library/results/' + project_name + '_OpEx_Breakdown.csv')
    
    # Gather the high-level results
    report_df = project.generate_report(metrics_configuration, project_name).T
    export_system = project.orbit.system_costs["ExportCableInstallation"]
    export_installation = project.orbit.installation_costs["ExportCableInstallation"]
    capex_sans_export = project.orbit.total_capex - export_system - export_installation
    additional_reporting = pd.DataFrame(
        [
            ["FCR (%)", project.fixed_charge_rate],
            ["Offtake Price ($/MWh)", project.offtake_price],
            ["System CapEx for Export Cables ($)", export_system],
            ["Installation CapEx for Export Cables ($)", export_installation],
            ["CapEx Without Export Cables ($)", capex_sans_export],
            ["Annual OpEx per kW ($/kW)", report_df.loc["OpEx per kW ($/kW)", project_name] / project.operations_years],
        ],
        columns=["Project"] + report_df.columns.tolist(),
    ).set_index("Project")
    report_df = pd.concat((report_df, additional_reporting), axis=0).loc[metrics_order]

    # Gather the detailed results
    monthly_results = project.cash_flow(breakdown=True).join(project.energy_production(frequency="month-year")).fillna(0)
    monthly_results = monthly_results.assign(
        CapEx_Installation=monthly_results[[c for c in monthly_results if c.startswith("CapEx") and c.endswith("Installation")]].sum(axis=1),
        CapEx_System=monthly_results[[c for c in monthly_results if c.startswith("CapEx") and c.endswith("System")]].sum(axis=1),
    )

    # monthly_results.to_csv(library_path / "results" / f"{project_name.lower().replace(' ', '_')}_monthly_detailed_results.csv")
    monthly_results["CapEx ($)"] = monthly_results[["CapEx_Installation", "CapEx_Soft", "CapEx_Project", "CapEx_System", "CapEx_Turbine"]].sum(axis=1)
    monthly_results = monthly_results.rename(columns={"OpEx": "OpEx ($)","Revenue": "Revenue ($)", "cash_flow": "Cash Flow ($)"})[final_cols]

    if "ExportSystemDesign" in project.orbit._phases:
        export = "ExportSystemDesign"
    else:
        export = "ElectricalDesign"

    # Create the inputs data
    inputs = pd.DataFrame(
        [
            ["FCR", project.fixed_charge_rate],
            ["Discount rate (%)", project.discount_rate],
            ["# Turbines", project.n_turbines()],
            ["Turbine Rating (MW)", project.turbine_rating()],
            ["Project Capacity (MW)", project.capacity("mw")],
            ["# OSS", project.n_substations()],
            ["Substructure type", "??"],
            ["Row spacing (rotor diameters)", "not used for custom layouts"],
            ["Turbine spacing (rotor diameters)", "not used for custom layouts"],
            ["Depth (m)", project.orbit.config["site"]["depth"]],
            [
                "Mean wind speed (m/s)",
                project.weather.loc[
                    project.orbit_start_date: project.wombat.env.end_datetime,
                    "windspeed_100m"
                ].mean()
            ],
            ["Distance to landfall (km)", project.orbit.config["site"]["distance_to_landfall"]],
            ["Distance to port (km)", project.wombat.config.port_distance],
            ["Interconnection distance (km)", project.orbit._phases[export]._distance_to_interconnection],
            ["# of POIs", "??"],
            ["Export cable type", [*project.orbit._phases[export].cable_lengths_by_type]],
            ["Array cable type", [*project.orbit._phases["CustomArraySystemDesign"].cable_lengths_by_type]],
        ],
        columns=["Inputs", f"{project_name}"]
    ).set_index("Inputs")

    # Save the outputs
    report_df.index.name = "Metrics"
    wrong_indexes = ["Offtake Price ($/MWh)", "System CapEx for Export Cables ($)", "Installation CapEx for Export Cables ($)", "CapEx Without Export Cables ($)", "IRR (%)", "NPV ($)"]
    
    
    return report_df.drop(wrong_indexes,axis=0)

# Extract AEP and OpEx Outputs - Multiple Runs
Availability and OpEx varies depending on the run as it uses probabilistic functions, so we collect the data from 5 runs and calculate the average OpEx and AEP

In [3]:
def display_results_all_runs(n_runs):
    import pandas as pd

    df_list_fixed = list()
    df_final_list = list()
    count = 0
    project = ["COE_2022_fixed_bottom_ERA5_2007_2013", "COE_2022_fixed_bottom_WTK_2007_2013", "COE_2022_fixed_bottom_NOW_23_2007_2013"]
    for i in project:
        df_2 = extract_results(i)
        
        if count == 0:
            df_list_fixed = df_2
        else:
            df_list_fixed = pd.concat([df_list_fixed, df_2], axis=1)
            
        count = count + 1
    
    return df_list_fixed

summary_results = display_results_all_runs(1)

ORBIT library intialized at 'C:\COWER\WHaLE\examples\library'

UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,operations,port_fees,equipment_cost,total_labor_cost,materials_cost,OpEx
year,,,,,,
2007,"3,600,000.0000",0,"25,860,607.2687",0,"735,504.0000","30,196,111.2687"
2008,"3,609,863.0137",0,"16,807,901.3135",0,"480,232.0000","20,897,996.3272"
2009,"3,600,000.0000",0,"68,620,934.0267",0,"1,153,504.0000","73,374,438.0267"
2010,"3,600,000.0000",0,"51,898,513.8572",0,"1,498,600.0000","56,997,113.8572"
2011,"3,600,000.0000",0,"37,975,716.1260",0,"1,052,560.0000","42,628,276.1260"
2012,"3,609,863.0137",0,"57,564,039.5440",0,"1,254,584.0000","62,428,486.5577"
2013,"3,600,000.0000",0,"62,402,275.9098",0,"1,167,312.0000","67,169,587.9098"

UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,operations,port_fees,equipment_cost,total_labor_cost,materials_cost,OpEx
year,,,,,,
2007,"3,600,000.0000",0,"25,860,607.2687",0,"735,504.0000","30,196,111.2687"
2008,"3,609,863.0137",0,"16,807,901.3135",0,"480,232.0000","20,897,996.3272"
2009,"3,600,000.0000",0,"68,620,934.0267",0,"1,153,504.0000","73,374,438.0267"
2010,"3,600,000.0000",0,"51,898,513.8572",0,"1,498,600.0000","56,997,113.8572"
2011,"3,600,000.0000",0,"37,975,716.1260",0,"1,052,560.0000","42,628,276.1260"
2012,"3,609,863.0137",0,"57,564,039.5440",0,"1,254,584.0000","62,428,486.5577"
2013,"3,600,000.0000",0,"62,402,275.9098",0,"1,167,312.0000","67,169,587.9098"

UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,operations,port_fees,equipment_cost,total_labor_cost,materials_cost,OpEx
year,,,,,,
2007,"3,600,000.0000",0,"25,860,607.2687",0,"735,504.0000","30,196,111.2687"
2008,"3,609,863.0137",0,"16,807,901.3135",0,"480,232.0000","20,897,996.3272"
2009,"3,600,000.0000",0,"68,620,934.0267",0,"1,153,504.0000","73,374,438.0267"
2010,"3,600,000.0000",0,"51,898,513.8572",0,"1,498,600.0000","56,997,113.8572"
2011,"3,600,000.0000",0,"37,975,716.1260",0,"1,052,560.0000","42,628,276.1260"
2012,"3,609,863.0137",0,"57,564,039.5440",0,"1,254,584.0000","62,428,486.5577"
2013,"3,600,000.0000",0,"62,402,275.9098",0,"1,167,312.0000","67,169,587.9098"

In [4]:
display(summary_results)

,COE_2022_fixed_bottom_ERA5_2007_2013,COE_2022_fixed_bottom_WTK_2007_2013,COE_2022_fixed_bottom_NOW_23_2007_2013
Metrics,,,
# Turbines,50.0000,50.0000,50.0000
Turbine Rating (MW),12.0000,12.0000,12.0000
Project Capacity (MW),600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680
Total Array Cable Length (km),277.9831,277.9831,277.9831
FCR (%),0.0569,0.0569,0.0569
CapEx ($),"2,290,237,187.4358","2,290,237,187.4358","2,290,237,187.4358"
CapEx per kW ($/kW),"3,817.0620","3,817.0620","3,817.0620"
OpEx ($),"353,692,010.0731","353,692,010.0731","353,692,010.0731"
OpEx per kW ($/kW),589.4867,589.4867,589.4867
Annual OpEx per kW ($/kW),84.2124,84.2124,84.2124
Energy Availability (%),0.9353,0.9353,0.9353
Gross Capacity Factor (%),0.5261,0.5396,0.5548
Net Capacity Factor Without Unmodeled Losses (%),0.4976,0.5104,0.5247
Net Capacity Factor With All Losses (%),0.4450,0.4565,0.4693
AEP (MWh),"2,340,650.6044","2,401,130.8574","2,468,308.8416"
AEP per kW (MWh/kW),3.9011,4.0019,4.1138
LCOE ($/MWh),77.2614,75.3153,73.2655

In [6]:
summary_results.to_csv('library/results/weather_databases_fixed_bottom_AEP_summary_results.csv')

In [7]:
def display_results_all_runs_all_data(n_runs):
    import pandas as pd

    df_list_fixed = list()
    df_final_list = list()
    count = 0
    project = ["COE_2022_fixed_bottom_ERA5_1959_2022", "COE_2022_fixed_bottom_WTK_2007_2013", "COE_2022_fixed_bottom_NOW_23_2000_2020"]
    for i in project:
        df_2 = extract_results(i)
        
        if count == 0:
            df_list_fixed = df_2
        else:
            df_list_fixed = pd.concat([df_list_fixed, df_2], axis=1)
            
        count = count + 1
    
    return df_list_fixed

summary_results = display_results_all_runs_all_data(1)

UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,operations,port_fees,equipment_cost,total_labor_cost,materials_cost,OpEx
year,,,,,,
1959,"3,600,000.0000",0,"20,862,313.6170",0,"449,600.0000","24,911,913.6170"
1960,"3,609,863.0137",0,"17,780,940.9087",0,"124,000.0000","21,514,803.9224"
1961,"3,600,000.0000",0,"64,943,670.0991",0,"977,800.0000","69,521,470.0991"
1962,"3,600,000.0000",0,"33,258,722.4457",0,"753,200.0000","37,611,922.4457"
1963,"3,600,000.0000",0,"40,146,193.2925",0,"488,200.0000","44,234,393.2925"
1964,"3,609,863.0137",0,"64,866,686.2316",0,"938,800.0000","69,415,349.2453"
1965,"3,600,000.0000",0,"48,411,473.8221",0,"522,600.0000","52,534,073.8221"
1966,"3,600,000.0000",0,"27,730,235.2632",0,"326,000.0000","31,656,235.2632"
1967,"3,600,000.0000",0,"45,359,227.9458",0,"276,600.0000","49,235,827.9458"
1968,"3,609,863.0137",0,"16,705,663.5952",0,"238,000.0000","20,553,526.6088"
1969,"3,600,000.0000",0,"48,918,417.0526",0,"566,600.0000","53,085,017.0526"
1970,"3,600,000.0000",0,"44,889,091.9875",0,"863,600.0000","49,352,691.9875"
1971,"3,600,000.0000",0,"66,060,711.6489",0,"597,400.0000","70,258,111.6489"
1972,"3,609,863.0137",0,"56,657,679.9437",0,"926,000.0000","61,193,542.9574"
1973,"3,600,000.0000",0,"66,952,576.6501",0,"815,800.0000","71,368,376.6501"
1974,"3,600,000.0000",0,"28,159,063.7818",0,"264,000.0000","32,023,063.7818"
1975,"3,600,000.0000",0,"46,526,230.7016",0,"496,600.0000","50,622,830.7016"
1976,"3,609,863.0137",0,"63,899,240.0069",0,"814,400.0000","68,323,503.0206"
1977,"3,600,000.0000",0,"46,593,442.3560",0,"444,600.0000","50,638,042.3560"
1978,"3,600,000.0000",0,"43,995,774.9784",0,"705,600.0000","48,301,374.9784"
1979,"3,600,000.0000",0,"59,452,034.4205",0,"522,600.0000","63,574,634.4205"
1980,"3,609,863.0137",0,"55,586,755.3279",0,"894,800.0000","60,091,418.3416"
1981,"3,600,000.0000",0,"88,188,184.3753",0,"861,400.0000","92,649,584.3753"
1982,"3,600,000.0000",0,"70,230,668.1892",0,"678,000.0000","74,508,668.1892"
1983,"3,600,000.0000",0,"95,794,946.3593",0,"1,119,800.0000","100,514,746.3593"
1984,"3,609,863.0137",0,"62,445,424.1047",0,"688,000.0000","66,743,287.1184"
1985,"3,600,000.0000",0,"89,256,087.8255",0,"1,462,200.0000","94,318,287.8255"
1986,"3,600,000.0000",0,"77,450,641.7608",0,"1,084,000.0000","82,134,641.7608"
1987,"3,600,000.0000",0,"89,023,551.3093",0,"847,800.0000","93,471,351.3093"
1988,"3,609,863.0137",0,"60,701,916.3672",0,"788,000.0000","65,099,779.3809"
1989,"3,600,000.0000",0,"88,215,216.5393",0,"1,316,200.0000","93,131,416.5393"
1990,"3,600,000.0000",0,"88,206,461.6673",0,"961,600.0000","92,768,061.6673"
1991,"3,600,000.0000",0,"89,341,009.6721",0,"795,800.0000","93,736,809.6721"
1992,"3,609,863.0137",0,"78,193,260.4062",0,"1,220,800.0000","83,023,923.4199"
1993,"3,600,000.0000",0,"88,656,045.8086",0,"742,600.0000","92,998,645.8086"
1994,"3,600,000.0000",0,"90,585,837.4502",0,"1,414,000.0000","95,599,837.4502"
1995,"3,600,000.0000",0,"96,900,802.0952",0,"1,166,200.0000","101,667,002.0952"
1996,"3,609,863.0137",0,"94,995,831.9038",0,"1,386,400.0000","99,992,094.9175"
1997,"3,600,000.0000",0,"108,552,967.0898",0,"1,270,600.0000","113,423,567.0898"
1998,"3,600,000.0000",0,"88,362,071.0620",0,"1,317,600.0000","93,279,671.0620"
1999,"3,600,000.0000",0,"103,762,976.0632",0,"1,183,400.0000","108,546,376.0632"
2000,"3,609,863.0137",0,"99,727,695.2420",0,"3,509,648.0000","106,847,206.2557"
2001,"3,600,000.0000",0,"93,718,734.0285",0,"1,784,152.0000","99,102,886.0285"
2002,"3,600,000.0000",0,"76,019,480.3470",0,"1,065,072.0000","80,684,552.3470"
2003,"3,600,000.0000",0,"100,829,252.5090",0,"2,132,200.0000","106,561,452.5090"
2004,"3,609,863.0137",0,"98,083,087.9467",0,"2,473,232.0000","104,166,182.9604"
2005,"3,600,000.0000",0,"103,553,319.7570",0,"2,629,144.0000","109,782,463.7570"
2006,"3,600,000.0000",0,"98,988,805.4462",0,"2,256,704.0000","104,845,509.4462"
2007,"3,600,000.0000",0,"91,136,204.8610",0,"2,120,056.0000","96,856,260.8610"
2008,"3,609,863.0137",0,"91,249,303.9565",0,"2,390,176.0000","97,249,342.9702"
2009,"3,600,000.0000",0,"99,012,804.8269",0,"2,607,080.0000","105,219,884.8269"
2010,"3,600,000.0000",0,"98,307,925.1872",0,"2,572,720.0000","104,480,645.1872"
2011,"3,600,000.0000",0,"102,862,165.7186",0,"2,685,864.0000","109,148,029.7186"
2012,"3,609,863.0137",0,"87,185,573.3997",0,"2,158,032.0000","92,953,468.4134"
2013,"3,600,000.0000",0,"89,268,719.6382",0,"2,336,264.0000","95,204,983.6382"
2014,"3,600,000.0000",0,"102,764,181.3251",0,"2,391,904.0000","108,756,085.3251"
2015,"3,600,000.0000",0,"96,089,692.5996",0,"2,571,112.0000","102,260,804.5996"
2016,"3,609,863.0137",0,"103,626,285.1501",0,"2,487,392.0000","109,723,540.1638"
2017,"3,600,000.0000",0,"104,518,770.2374",0,"2,525,352.0000","110,644,122.2374"
2018,"3,600,000.0000",0,"110,509,258.4409",0,"2,326,000.0000","116,435,258.4409"
2019,"3,600,000.0000",0,"96,136,067.8214",0,"2,567,800.0000","102,303,867.8214"
2020,"3,609,863.0137",0,"112,838,880.6720",0,"2,935,696.0000","119,384,439.6857"
2021,"3,600,000.0000",0,"87,229,657.5777",0,"1,220,600.0000","92,050,257.5777"
2022,"3,600,000.0000",0,"96,371,501.2667",0,"1,138,400.0000","101,109,901.2667"

UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,operations,port_fees,equipment_cost,total_labor_cost,materials_cost,OpEx
year,,,,,,
2007,"3,600,000.0000",0,"24,779,996.0088",0,"741,504.0000","29,121,500.0088"
2008,"3,609,863.0137",0,"27,983,359.0514",0,"545,752.0000","32,138,974.0651"
2009,"3,600,000.0000",0,"63,680,565.6807",0,"1,135,024.0000","68,415,589.6807"
2010,"3,600,000.0000",0,"50,942,831.4034",0,"1,543,240.0000","56,086,071.4034"
2011,"3,600,000.0000",0,"42,560,506.9646",0,"768,480.0000","46,928,986.9646"
2012,"3,609,863.0137",0,"41,050,734.8964",0,"1,139,064.0000","45,799,661.9101"
2013,"3,600,000.0000",0,"52,414,423.0955",0,"1,105,344.0000","57,119,767.0955"

UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.UserWarning: C:\Users\dmulash\.conda\envs\COWER\lib\site-packages\ORBIT\phases\design\array_system_design.py:906
Missing data in columns ['bury_speed']; all values will be calculated.

Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5
Correcting negative Overhang:-2.5

,operations,port_fees,equipment_cost,total_labor_cost,materials_cost,OpEx
year,,,,,,
2000,"3,609,863.0137",0,"28,540,191.9684",0,"741,024.0000","32,891,078.9821"
2001,"3,600,000.0000",0,"19,089,341.0630",0,"500,952.0000","23,190,293.0630"
2002,"3,600,000.0000",0,"60,787,783.3586",0,"1,153,424.0000","65,541,207.3586"
2003,"3,600,000.0000",0,"48,961,915.2294",0,"1,418,680.0000","53,980,595.2294"
2004,"3,609,863.0137",0,"39,802,603.7985",0,"767,360.0000","44,179,826.8122"
2005,"3,600,000.0000",0,"55,018,890.0945",0,"1,016,344.0000","59,635,234.0945"
2006,"3,600,000.0000",0,"59,082,751.5139",0,"1,173,312.0000","63,856,063.5139"
2007,"3,600,000.0000",0,"28,092,964.0969",0,"813,400.0000","32,506,364.0969"
2008,"3,609,863.0137",0,"25,598,564.3930",0,"592,800.0000","29,801,227.4067"
2009,"3,600,000.0000",0,"31,348,619.4445",0,"727,192.0000","35,675,811.4445"
2010,"3,600,000.0000",0,"65,024,737.8060",0,"1,205,376.0000","69,830,113.8060"
2011,"3,600,000.0000",0,"44,672,842.5599",0,"1,216,672.0000","49,489,514.5599"
2012,"3,609,863.0137",0,"47,435,589.0277",0,"1,124,720.0000","52,170,172.0414"
2013,"3,600,000.0000",0,"53,012,249.4597",0,"1,803,144.0000","58,415,393.4597"
2014,"3,600,000.0000",0,"45,014,344.4611",0,"1,208,912.0000","49,823,256.4611"
2015,"3,600,000.0000",0,"81,171,935.3336",0,"1,384,440.0000","86,156,375.3336"
2016,"3,609,863.0137",0,"58,191,317.5678",0,"1,046,392.0000","62,847,572.5815"
2017,"3,600,000.0000",0,"64,930,195.8679",0,"1,137,152.0000","69,667,347.8679"
2018,"3,600,000.0000",0,"63,610,812.2328",0,"1,417,712.0000","68,628,524.2328"
2019,"3,600,000.0000",0,"72,947,447.2175",0,"1,080,272.0000","77,627,719.2175"
2020,"3,609,863.0137",0,"45,353,822.6083",0,"1,173,072.0000","50,136,757.6220"

In [8]:
display(summary_results)

,COE_2022_fixed_bottom_ERA5_1959_2022,COE_2022_fixed_bottom_WTK_2007_2013,COE_2022_fixed_bottom_NOW_23_2000_2020
Metrics,,,
# Turbines,50.0000,50.0000,50.0000
Turbine Rating (MW),12.0000,12.0000,12.0000
Project Capacity (MW),600.0000,600.0000,600.0000
# OSS,1.0000,1.0000,1.0000
Total Export Cable Length (km),118.0680,118.0680,118.0680
Total Array Cable Length (km),277.9831,277.9831,277.9831
FCR (%),0.0569,0.0569,0.0569
CapEx ($),"2,290,237,187.4358","2,290,237,187.4358","2,290,237,187.4358"
CapEx per kW ($/kW),"3,817.0620","3,817.0620","3,817.0620"
OpEx ($),"5,213,401,022.2998","335,610,551.1282","1,136,050,449.1851"
OpEx per kW ($/kW),"8,689.0017",559.3509,"1,893.4174"
Annual OpEx per kW ($/kW),135.7657,79.9073,90.1627
Energy Availability (%),0.8700,0.9328,0.9264
Gross Capacity Factor (%),0.5381,0.5396,0.5607
Net Capacity Factor Without Unmodeled Losses (%),0.5219,0.5092,0.5262
Net Capacity Factor With All Losses (%),0.4681,0.4553,0.4701
AEP (MWh),"2,461,821.8015","2,394,742.4413","2,472,685.9194"
AEP per kW (MWh/kW),4.1030,3.9912,4.1211
LCOE ($/MWh),86.0232,74.4376,74.5797

In [9]:
summary_results.to_csv('library/results/weather_databases_all_years_fixed_bottom_AEP_summary_results.csv')